# Test server proxy port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "frontend/src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

PATHS:
  # Path to dist folder
  dist: "frontend/dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "frontend/src/assets/**/*"
    - "!frontend/src/assets/{img,js,scss}/**/*"
  # Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"
    - "bower_components/font-awesome/scss"
  css:
    - "bower_components/ng-sortable/dist/ng-sortable.css"
  fonts:
    - "bower_components/font-awesome/fonts/**/*"
  vendorJS:
    # Libraries requried by Foundation
    - "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    # Foundation components - optional if not used
    - "bower_components/foundation-sites/js/foundation.abide.js"
    - "bower_components/foundation-sites/js/foundation.accordion.js"
    - "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    - "bower_components/foundation-sites/js/foundation.drilldown.js"
    - "bower_components/foundation-sites/js/foundation.dropdown.js"
    - "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    - "bower_components/foundation-sites/js/foundation.equalizer.js"
    - "bower_components/foundation-sites/js/foundation.interchange.js"
    - "bower_components/foundation-sites/js/foundation.magellan.js"
    - "bower_components/foundation-sites/js/foundation.offcanvas.js"
    - "bower_components/foundation-sites/js/foundation.orbit.js"
    - "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    - "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    - "bower_components/foundation-sites/js/foundation.reveal.js"
    - "bower_components/foundation-sites/js/foundation.slider.js"
    - "bower_components/foundation-sites/js/foundation.sticky.js"
    - "bower_components/foundation-sites/js/foundation.tabs.js"
    - "bower_components/foundation-sites/js/foundation.toggler.js"
    - "bower_components/foundation-sites/js/foundation.tooltip.js"
    # Angular
    - "bower_components/angular/angular.js"
    - "bower_components/angular-ui-router/release/angular-ui-router.js"
     # Angular animations
    - "bower_components/angular-animate/angular-animate.js"
    # Libraries used by the app
    - "bower_components/jshashtable/hashtable.js"
    - "bower_components/jshashset/hashset.js"
    - "bower_components/ng-sortable/dist/ng-sortable.js"
    - "bower_components/angular-mass-autocomplete/massautocomplete.js"
    - "bower_components/fuse.js/src/fuse.js"
  javascript:
    - "frontend/src/assets/js/!(app).js"
    - "frontend/src/assets/js/**"
    - "frontend/src/assets/js/app.js"
